### ISSUE TITLE
task_build_dist 无法使用 gulp-fontmin

### ISSUE THREAD

**Issue by Loyalsoldier** [TmT/WxMoment-Workflow#2]
最近用这个 Workflow 时，发现无法使用 gulp-fontmin，报错如下：

![_20151004144946](https://cloud.githubusercontent.com/assets/10487845/10266757/5b1fb112-6aa7-11e5-9688-52320d4eae8f.png)

**意思是字体文件太大了？**

[gulp-fontmin](https://github.com/ecomfe/gulp-fontmin) 在 `gulp build_dist` 里的代码如下：

![1](https://cloud.githubusercontent.com/assets/10487845/10266774/56436778-6aa8-11e5-93fb-d803eb3965a8.png)

![2](https://cloud.githubusercontent.com/assets/10487845/10266775/591f5222-6aa8-11e5-9a15-743ee31874f1.png)

---

**我配置的完整`task_build_dist`文件[戳这里](https://gist.github.com/Loyalsoldier/449cf85e1544ca4844a3)**

---
## gulp-fontmin 官方的代码示例：

![3](https://cloud.githubusercontent.com/assets/10487845/10266779/8dba608a-6aa8-11e5-80b3-7187d6896b7b.png)

**Comment by willerce** [comment]
这个问题与 tmt workflow 无关。
我觉得在 async series 方法中，你的 cb 调用有误，应该是所有的 HTML 的 fontmin 结束后再调用 cb 。

**Comment by Loyalsoldier** [comment]
@willerce 

成功了，这样写就好了：

![1](https://cloud.githubusercontent.com/assets/10487845/10277782/ff8d34e8-6b8a-11e5-8de5-6f35c2be5236.png)
